---
grails:
  profile: web-plugin
  codegen:
    defaultPackage: au.org.ala.bie
  spring:
    transactionManagement:
      proxies: false
  gorm:
    # Whether to autowire entities.
    # Disabled by default for performance reasons.
    autowire: false
    reactor:
      # Whether to translate GORM events into Reactor events
      # Disabled by default for performance reasons
      events: false
info:
  app:
    name: '@info.app.name@'
    version: '@info.app.version@'
    grailsVersion: '@info.app.grailsVersion@'
spring:
  main:
    banner-mode: "off"
  groovy:
    template:
      check-template-location: false

# Spring Actuator Endpoints are Disabled by Default
endpoints:
  enabled: true
  jmx:
    enabled: true

---
grails:
  cors:
    enabled: true
  mime:
    disable:
      accept:
        header:
          userAgents:
            - Gecko
            - WebKit
            - Presto
            - Trident
    types:
      all: '*/*'
      atom: application/atom+xml
      css: text/css
      csv: text/csv
      form: application/x-www-form-urlencoded
      html:
        - text/html
        - application/xhtml+xml
      js: text/javascript
      json:
        - application/json
        - text/json
      multipartForm: multipart/form-data
      pdf: application/pdf
      rss: application/rss+xml
      text: text/plain
      hal:
        - application/hal+json
        - application/hal+xml
      xml:
        - text/xml
        - application/xml
  urlmapping:
    cache:
      maxsize: 1000
  controllers:
    defaultScope: singleton
  converters:
    encoding: UTF-8
  views:
    default:
      codec: html
    gsp:
      encoding: UTF-8
      htmlcodec: xml
      codecs:
        expression: html
        scriptlets: html
        taglib: none
        staticparts: none
endpoints:
  jmx:
    unique-names: true
---
#Required so that the gbif-ecat library does not bugger up initialisation from its internal application.properties
app:
  name: bie-plugin
  dataDir: /tmp/gbif-ecat
skin:
  layout: generic
  orgNameLong: BIE Plugin
  orgNameShort: BIE
  fluidLayout: false
bie:
  baseURL: http://dev.ala.org.au:8080
  searchPath: /search
  index:
    url: https://bie-ws.ala.org.au/ws
facets: idxtype,rank,speciesGroup,locatedInHubCountry,imageAvailable
speciesParent: https://lists.ala.org.au/iconic-species
serverName: http://dev.ala.org.au:8080
projectNameShort: ALA
projectName: Atlas of Living Australia
biocache:
  baseURL: "http://biocache.ala.org.au"
biocacheService:
  baseURL: http://biocache.ala.org.au/ws
  queryContext:
spatial:
  baseURL: http://spatial.ala.org.au
layersService:
  baseURL: http://spatial.ala.org.au/ws
ala:
  baseURL: http://www.ala.org.au
collectory:
  baseURL: http://collections.ala.org.au
  threatenedSpeciesCodesUrl: http://collections.ala.org.au/public/showDataResource
regions:
  baseURL: http://regions.ala.org.au
speciesList:
  baseURL: http://lists.ala.org.au
alerts:
  baseUrl: http://alerts.ala.org.au/ws/
sightings:
  guidUrl: http://sightings.ala.org.au/
eol:
  lang: en
defaultDecimalLatitude: -25.61
defaultDecimalLongitude: 134.35
defaultZoomLevel: 4
image:
  thumbnailUrl: http://images.ala.org.au/image/proxyImageThumbnail?imageId=
map:
  default:
    id:
    token:
    url: http://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}.png
    attr: Map data &copy; <a href='http://www.openstreetmap.org/copyright'>OpenStreetMap</a>, imagery &copy; <a href='http://cartodb.com/attributions'>CartoDB</a>
    domain: abcd
    colour: e6704c
  simpleMapButton: false
  records:
    colour: e6704c
bieService:
  queryContext:
googleMapsApiKey: <key value>
geocode.querySuffix:
occurrenceCounts:
  enabled: true
additionalResultsFields: kingdom
admin_role: ROLE_ADMIN
allowedImageEditingRoles: ROLE_ADMIN
additionalMapFilter:
synonymsTypes: synonym
vernacularName:
  # A category of vernacular names pulled out from the standard list and given special display treatment
  pull:
    categories:
    active: false
    label: Special Common Names
    labelDetail: Common names with a special status
    showHeader: false
    showLanguage: false
external:
  eol:
    search:
      # {0}= name to search for, {1} = filter string
      # service: https://eol.org/api/search/1.0.json?q={0}&page=1&exact=true&filter_by_string={1}&cache_ttl=
      service: https://eol.org/api/search/1.0.json?q={0}&page=1&exact=true&cache_ttl=
    page:
      # {0} = page id
      service: https://eol.org/api/pages/1.0/{0,number,#0}.json?images_per_page=0&videos_per_page=0&sounds_per_page=0&maps_per_page=0&texts_per_page=30&subjects=overview&licenses=all&details=true&references=true&vetted=0&cache_ttl=
literature:
  bhl:
    url: https://biodiversitylibrary.org
    api: https://www.biodiversitylibrary.org/api3
    apikey: "<key value>"
    fulltext: false
    pageSize: 200
    extend: false
  genbank:
    url: https://www.ncbi.nlm.nih.gov
  scholar:
    url: https://scholar.google.com
  trove:
    url: https://trove.nla.gov.au
    api: https://api.trove.nla.gov.au
    apikey: "<key value>"
show:
  tabs: overview,gallery,names,classification,records,literature,sequences,data-partners
