runWithNoExternalConfig = true
projectNameShort = "Atlas"
projectName = "Atlas of Living Australia"
bie.baseURL = "http://localhost:8090/bie-plugin"
bie.searchPath = "/search"
//biocache.baseURL = "http://biocache.ala.org.au"
//biocacheService.baseURL = "http://biocache.ala.org.au/ws"
biocache.baseURL = "http://biocache.ala.org.au"
biocacheService.baseURL = "http://biocache.ala.org.au/ws"
biocacheService.queryContext = ""
spatial.baseURL = "http://spatial.ala.org.au"
layersService.baseURL = "http://spatial.ala.org.au/ws"
ala.baseURL = "http://www.ala.org.au"
collectory.baseURL = "http://collections.ala.org.au"
regions.baseURL = "http://regions.ala.org.au"
bhl.baseURL = "http://bhlidx.ala.org.au"
//speciesList.baseURL = "http://lists.ala.org.au"
speciesList.baseURL = "http://lists.ala.org.au"
alerts.baseUrl = "http://alerts.ala.org.au/ws/"
sightings.guidUrl = "http://sightings.ala.org.au/"
collectory.threatenedSpeciesCodesUrl = collectory.baseURL + "/public/showDataResource"
skin.layout = "generic"
skin.orgNameLong = "Generic BIE"
skin.orgNameShort = "BIE"
eol.lang = "en"
//bie.index.url = "http://bie.ala.org.au/ws"
bie.index.url = "http://localhost:8080/"
defaultDecimalLatitude=-25.61
defaultDecimalLongitude=134.35
defaultZoomLevel=4
image.thumbnailUrl = "http://images.ala.org.au/image/proxyImageThumbnail?imageId="
facets = "idxtype,rank,locatedInHubCountry,imageAvailable,speciesGroup,taxonomicStatus"
map.default.id = "" // not needed for CartoDB map
map.default.token = "" // not needed for CartoDB map
map.default.url = "http://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}.png"
map.default.attr = "Map data &copy; <a href='http://www.openstreetmap.org/copyright'>OpenStreetMap</a>, imagery &copy; <a href='http://cartodb.com/attributions'>CartoDB</a>"
map.default.domain = "abcd"
map.records.colour = "e6704c"
map.simpleMapButton = false
bieService.queryContext = ""
googleMapsApiKey = "AIzaSyB0HIkSCV2EdkG50uM7s96IEbO6wUHTqy0"
languageCodesUrl = defaultConfig.class.getResource("/languages.json").toString()
geocode.querySuffix = ""
occurrenceCounts.enabled = true
additionalResultsFields = "kingdom"
admin_role = "ROLE_ADMIN"
/** an additional map filter that can be applied to restrict records displayed on the map */
additionalMapFilter=""
synonymsTypes="synonym" // comma separated list
speciesParent="${bie.baseURL}"