runWithNoExternalConfig = true
projectNameShort = "Atlas"
projectName = "Atlas of Living Australia"
bie.baseURL = "http://bie.ala.org.au"
bie.searchPath = "/search"
biocache.baseURL = "http://biocache.ala.org.au"
biocacheService.baseURL = "http://biocache.ala.org.au/ws"
spatial.baseURL = "http://spatial.ala.org.au"
ala.baseURL = "http://www.ala.org.au"
collectory.baseURL = "http://collections.ala.org.au"
bhl.baseURL = "http://bhlidx.ala.org.au"
speciesList.baseURL = "http://lists.ala.org.au"
alerts.baseUrl = "http://alerts.ala.org.au/ws/"
sightings.guidUrl = "http://sightings.ala.org.au/"
collectory.threatenedSpeciesCodesUrl = collectory.baseURL + "/public/showDataResource"
skin.layout = "generic"
eol.lang = "en"
bie.index.url = "http://localhost:8080/bie-index"
defaultDecimalLatitude = -27.7
defaultDecimalLongitude = 133.8
defaultZoomLevel = 4
image.thumbnailUrl = "http://images.ala.org.au/image/proxyImageThumbnail?imageId="